packages:
  - apps/*
  - packages/*
overrides:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.7
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  sharp: false
  unrs-resolver: false
